# SwiftLint Configuration for VectorDataStore

# Paths to include/exclude
included:
  - Sources
  - Tests

excluded:
  - .build
  - .swiftpm
  - Packages

# Disable rules
disabled_rules:
  - trailing_whitespace
  - todo # Allow TODO comments during development

# Opt-in rules
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

function_parameter_count:
  warning: 5
  error: 8

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 2
    error: 3

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - tx
    - i
    - j
    - k
    - db
    - in
    - on
    - to
    - at
    - _

type_name:
  min_length: 3
  max_length:
    warning: 50
    error: 60
  excluded:
    - ID

large_tuple:
  warning: 3
  error: 4

# Custom rules
custom_rules:
  no_objcMembers:
    name: "@objcMembers"
    regex: "@objcMembers"
    message: "Avoid using @objcMembers"
    severity: warning
  
  no_direct_standard_output:
    name: "No direct standard output"
    regex: "(print|dump)\\("
    match_kinds:
      - identifier
    message: "Use proper logging instead of print"
    severity: warning

# Force unwrapping should be avoided
force_unwrapping: error

# Trailing closure
trailing_closure:
  only_single_muted_parameter: true

# Empty count
empty_count:
  severity: error
